apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: egcmixkg7-nodejs
  janus-idp.io/tekton: egcmixkg7-nodejs
  backstage.io/kubernetes-id: egcmixkg7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: egcmixkg7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
